/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SearchBar {
        "buttonClass": string;
        "inputClass": string;
    }
}
declare global {
    interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {
    }
    var HTMLSearchBarElement: {
        prototype: HTMLSearchBarElement;
        new (): HTMLSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "search-bar": HTMLSearchBarElement;
    }
}
declare namespace LocalJSX {
    interface SearchBar {
        "buttonClass"?: string;
        "inputClass"?: string;
        "onEmitSearchText"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "search-bar": SearchBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "search-bar": LocalJSX.SearchBar & JSXBase.HTMLAttributes<HTMLSearchBarElement>;
        }
    }
}
